- name: Update all packages on remote hosts
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update packages on Debian/Ubuntu
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update packages on RedHat/CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update packages on Fedora
      dnf:
        name: '*'
        state: latest
      when: ansible_distribution == "Fedora"
